add lesson-3 tasks
alesiabalan/js-home-tasks-balan pull request #2
Opened 2022-02-11 10:36 UTC by alesiabalan

2022-02-13 12:21 UTC, instinct-it-academy requested changes
Добрый день, практически все хорошо. Пока что на небольшую доработку. Обратите внимание на комментарии.

2022-02-13 12:21 UTC, instinct-it-academy commented on lesson-3-code-execution/task1.js
> +    max = Math.max(tasksCompleted[key]);
не уверен в необходимости max в данном случае, учитывая что Вы передаёте только одно значение. Можете пояснить как предполагали что будет работать ?)

2022-02-13 12:21 UTC, instinct-it-academy commented on lesson-3-code-execution/task3.js
> +    if (num === "" || num === null || !isFinite(num)) break;
тут есть 2 момента:

- было бы хорошо сделать проверку явной, вынесите пожалуйста эту проверку на уровень цикла;
- не использовали {} , не пропускайте пожалуйста так же как и ;.

2022-02-14 13:46 UTC, alesiabalan commented on lesson-3-code-execution/task1.js
> +    max = Math.max(tasksCompleted[key]);
не могу пояснить) перебор дошёл до последнего значения, оно максимальное, и я решила, что всё работает. Исправила, теперь работает

2022-02-19 11:08 UTC, instinct-it-academy approved these changes
Добрый день, принято

2022-02-19 11:08 UTC, merged